//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Auth.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Sh_Generated_AuthServiceregisterCall: ClientCallUnary {}

fileprivate final class Sh_Generated_AuthServiceregisterCallBase: ClientCallUnaryBase<Sh_Generated_AuthRequest, Sh_Generated_AuthResponse>, Sh_Generated_AuthServiceregisterCall {
  override class var method: String { return "/sh.generated.AuthService/register" }
}

internal protocol Sh_Generated_AuthServiceloginCall: ClientCallUnary {}

fileprivate final class Sh_Generated_AuthServiceloginCallBase: ClientCallUnaryBase<Sh_Generated_AuthRequest, Sh_Generated_AuthResponse>, Sh_Generated_AuthServiceloginCall {
  override class var method: String { return "/sh.generated.AuthService/login" }
}

internal protocol Sh_Generated_AuthServicelogoutCall: ClientCallUnary {}

fileprivate final class Sh_Generated_AuthServicelogoutCallBase: ClientCallUnaryBase<Sh_Generated_LogoutRequest, Sh_Generated_LogoutResponse>, Sh_Generated_AuthServicelogoutCall {
  override class var method: String { return "/sh.generated.AuthService/logout" }
}


/// Instantiate Sh_Generated_AuthServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Sh_Generated_AuthServiceService: ServiceClient {
  /// Synchronous. Unary.
  func register(_ request: Sh_Generated_AuthRequest) throws -> Sh_Generated_AuthResponse
  /// Asynchronous. Unary.
  func register(_ request: Sh_Generated_AuthRequest, completion: @escaping (Sh_Generated_AuthResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServiceregisterCall

  /// Synchronous. Unary.
  func login(_ request: Sh_Generated_AuthRequest) throws -> Sh_Generated_AuthResponse
  /// Asynchronous. Unary.
  func login(_ request: Sh_Generated_AuthRequest, completion: @escaping (Sh_Generated_AuthResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServiceloginCall

  /// Synchronous. Unary.
  func logout(_ request: Sh_Generated_LogoutRequest) throws -> Sh_Generated_LogoutResponse
  /// Asynchronous. Unary.
  func logout(_ request: Sh_Generated_LogoutRequest, completion: @escaping (Sh_Generated_LogoutResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServicelogoutCall

}

internal final class Sh_Generated_AuthServiceServiceClient: ServiceClientBase, Sh_Generated_AuthServiceService {
  /// Synchronous. Unary.
  internal func register(_ request: Sh_Generated_AuthRequest) throws -> Sh_Generated_AuthResponse {
    return try Sh_Generated_AuthServiceregisterCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func register(_ request: Sh_Generated_AuthRequest, completion: @escaping (Sh_Generated_AuthResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServiceregisterCall {
    return try Sh_Generated_AuthServiceregisterCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func login(_ request: Sh_Generated_AuthRequest) throws -> Sh_Generated_AuthResponse {
    return try Sh_Generated_AuthServiceloginCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func login(_ request: Sh_Generated_AuthRequest, completion: @escaping (Sh_Generated_AuthResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServiceloginCall {
    return try Sh_Generated_AuthServiceloginCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func logout(_ request: Sh_Generated_LogoutRequest) throws -> Sh_Generated_LogoutResponse {
    return try Sh_Generated_AuthServicelogoutCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func logout(_ request: Sh_Generated_LogoutRequest, completion: @escaping (Sh_Generated_LogoutResponse?, CallResult) -> Void) throws -> Sh_Generated_AuthServicelogoutCall {
    return try Sh_Generated_AuthServicelogoutCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

