//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: MapObject.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Sh_Generated_MapObjectServiceallObjectsCall: ClientCallUnary {}

fileprivate final class Sh_Generated_MapObjectServiceallObjectsCallBase: ClientCallUnaryBase<Sh_Generated_MapObjectRequest, Sh_Generated_MapObjectResponse>, Sh_Generated_MapObjectServiceallObjectsCall {
  override class var method: String { return "/sh.generated.MapObjectService/allObjects" }
}


/// Instantiate Sh_Generated_MapObjectServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Sh_Generated_MapObjectServiceService: ServiceClient {
  /// Synchronous. Unary.
  func allObjects(_ request: Sh_Generated_MapObjectRequest) throws -> Sh_Generated_MapObjectResponse
  /// Asynchronous. Unary.
  func allObjects(_ request: Sh_Generated_MapObjectRequest, completion: @escaping (Sh_Generated_MapObjectResponse?, CallResult) -> Void) throws -> Sh_Generated_MapObjectServiceallObjectsCall

}

internal final class Sh_Generated_MapObjectServiceServiceClient: ServiceClientBase, Sh_Generated_MapObjectServiceService {
  /// Synchronous. Unary.
  internal func allObjects(_ request: Sh_Generated_MapObjectRequest) throws -> Sh_Generated_MapObjectResponse {
    return try Sh_Generated_MapObjectServiceallObjectsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func allObjects(_ request: Sh_Generated_MapObjectRequest, completion: @escaping (Sh_Generated_MapObjectResponse?, CallResult) -> Void) throws -> Sh_Generated_MapObjectServiceallObjectsCall {
    return try Sh_Generated_MapObjectServiceallObjectsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

