//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Order.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Sh_Generated_OrderServiceavailableOrdersCall: ClientCallUnary {}

fileprivate final class Sh_Generated_OrderServiceavailableOrdersCallBase: ClientCallUnaryBase<Sh_Generated_AvailableOrdersRequest, Sh_Generated_OrdersResponse>, Sh_Generated_OrderServiceavailableOrdersCall {
  override class var method: String { return "/sh.generated.OrderService/availableOrders" }
}

internal protocol Sh_Generated_OrderServicesearchOrdersCall: ClientCallUnary {}

fileprivate final class Sh_Generated_OrderServicesearchOrdersCallBase: ClientCallUnaryBase<Sh_Generated_SearchOrdersRequest, Sh_Generated_OrdersResponse>, Sh_Generated_OrderServicesearchOrdersCall {
  override class var method: String { return "/sh.generated.OrderService/searchOrders" }
}


/// Instantiate Sh_Generated_OrderServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Sh_Generated_OrderServiceService: ServiceClient {
  /// Synchronous. Unary.
  func availableOrders(_ request: Sh_Generated_AvailableOrdersRequest) throws -> Sh_Generated_OrdersResponse
  /// Asynchronous. Unary.
  func availableOrders(_ request: Sh_Generated_AvailableOrdersRequest, completion: @escaping (Sh_Generated_OrdersResponse?, CallResult) -> Void) throws -> Sh_Generated_OrderServiceavailableOrdersCall

  /// Synchronous. Unary.
  func searchOrders(_ request: Sh_Generated_SearchOrdersRequest) throws -> Sh_Generated_OrdersResponse
  /// Asynchronous. Unary.
  func searchOrders(_ request: Sh_Generated_SearchOrdersRequest, completion: @escaping (Sh_Generated_OrdersResponse?, CallResult) -> Void) throws -> Sh_Generated_OrderServicesearchOrdersCall

}

internal final class Sh_Generated_OrderServiceServiceClient: ServiceClientBase, Sh_Generated_OrderServiceService {
  /// Synchronous. Unary.
  internal func availableOrders(_ request: Sh_Generated_AvailableOrdersRequest) throws -> Sh_Generated_OrdersResponse {
    return try Sh_Generated_OrderServiceavailableOrdersCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func availableOrders(_ request: Sh_Generated_AvailableOrdersRequest, completion: @escaping (Sh_Generated_OrdersResponse?, CallResult) -> Void) throws -> Sh_Generated_OrderServiceavailableOrdersCall {
    return try Sh_Generated_OrderServiceavailableOrdersCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func searchOrders(_ request: Sh_Generated_SearchOrdersRequest) throws -> Sh_Generated_OrdersResponse {
    return try Sh_Generated_OrderServicesearchOrdersCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func searchOrders(_ request: Sh_Generated_SearchOrdersRequest, completion: @escaping (Sh_Generated_OrdersResponse?, CallResult) -> Void) throws -> Sh_Generated_OrderServicesearchOrdersCall {
    return try Sh_Generated_OrderServicesearchOrdersCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

