//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Quests.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Sh_Generated_QuestsServicesearchCall: ClientCallUnary {}

fileprivate final class Sh_Generated_QuestsServicesearchCallBase: ClientCallUnaryBase<Sh_Generated_SearchQuestsRequest, Sh_Generated_SearchQuestsResponse>, Sh_Generated_QuestsServicesearchCall {
  override class var method: String { return "/sh.generated.QuestsService/search" }
}


/// Instantiate Sh_Generated_QuestsServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Sh_Generated_QuestsServiceService: ServiceClient {
  /// Synchronous. Unary.
  func search(_ request: Sh_Generated_SearchQuestsRequest) throws -> Sh_Generated_SearchQuestsResponse
  /// Asynchronous. Unary.
  func search(_ request: Sh_Generated_SearchQuestsRequest, completion: @escaping (Sh_Generated_SearchQuestsResponse?, CallResult) -> Void) throws -> Sh_Generated_QuestsServicesearchCall

}

internal final class Sh_Generated_QuestsServiceServiceClient: ServiceClientBase, Sh_Generated_QuestsServiceService {
  /// Synchronous. Unary.
  internal func search(_ request: Sh_Generated_SearchQuestsRequest) throws -> Sh_Generated_SearchQuestsResponse {
    return try Sh_Generated_QuestsServicesearchCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func search(_ request: Sh_Generated_SearchQuestsRequest, completion: @escaping (Sh_Generated_SearchQuestsResponse?, CallResult) -> Void) throws -> Sh_Generated_QuestsServicesearchCall {
    return try Sh_Generated_QuestsServicesearchCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

