// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Quests.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Sh_Generated_ShelterQuest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var order: Sh_Generated_ShelterOrder {
    get {return _storage._order ?? Sh_Generated_ShelterOrder()}
    set {_uniqueStorage()._order = newValue}
  }
  /// Returns true if `order` has been explicitly set.
  var hasOrder: Bool {return _storage._order != nil}
  /// Clears the value of `order`. Subsequent reads from it will return its default value.
  mutating func clearOrder() {_uniqueStorage()._order = nil}

  var steps: [Sh_Generated_ShelterQuestStep] {
    get {return _storage._steps}
    set {_uniqueStorage()._steps = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Sh_Generated_ShelterQuestStep {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var demand: Sh_Generated_ShelterDemand {
    get {return _storage._demand ?? Sh_Generated_ShelterDemand()}
    set {_uniqueStorage()._demand = newValue}
  }
  /// Returns true if `demand` has been explicitly set.
  var hasDemand: Bool {return _storage._demand != nil}
  /// Clears the value of `demand`. Subsequent reads from it will return its default value.
  mutating func clearDemand() {_uniqueStorage()._demand = nil}

  var venue: Sh_Generated_Venue {
    get {return _storage._venue ?? Sh_Generated_Venue()}
    set {_uniqueStorage()._venue = newValue}
  }
  /// Returns true if `venue` has been explicitly set.
  var hasVenue: Bool {return _storage._venue != nil}
  /// Clears the value of `venue`. Subsequent reads from it will return its default value.
  mutating func clearVenue() {_uniqueStorage()._venue = nil}

  var timeWindow: Sh_Generated_TimeWindow {
    get {return _storage._timeWindow ?? Sh_Generated_TimeWindow()}
    set {_uniqueStorage()._timeWindow = newValue}
  }
  /// Returns true if `timeWindow` has been explicitly set.
  var hasTimeWindow: Bool {return _storage._timeWindow != nil}
  /// Clears the value of `timeWindow`. Subsequent reads from it will return its default value.
  mutating func clearTimeWindow() {_uniqueStorage()._timeWindow = nil}

  var duration: Int32 {
    get {return _storage._duration}
    set {_uniqueStorage()._duration = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Sh_Generated_SearchQuestsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var params: Sh_Generated_SearchParams {
    get {return _storage._params ?? Sh_Generated_SearchParams()}
    set {_uniqueStorage()._params = newValue}
  }
  /// Returns true if `params` has been explicitly set.
  var hasParams: Bool {return _storage._params != nil}
  /// Clears the value of `params`. Subsequent reads from it will return its default value.
  mutating func clearParams() {_uniqueStorage()._params = nil}

  var orderTags: [String] {
    get {return _storage._orderTags}
    set {_uniqueStorage()._orderTags = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Sh_Generated_SearchQuestsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var quests: [Sh_Generated_ShelterQuest] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "sh.generated"

extension Sh_Generated_ShelterQuest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ShelterQuest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "order"),
    2: .same(proto: "steps"),
  ]

  fileprivate class _StorageClass {
    var _order: Sh_Generated_ShelterOrder? = nil
    var _steps: [Sh_Generated_ShelterQuestStep] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _order = source._order
      _steps = source._steps
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._order)
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._steps)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._order {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._steps.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._steps, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sh_Generated_ShelterQuest, rhs: Sh_Generated_ShelterQuest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._order != rhs_storage._order {return false}
        if _storage._steps != rhs_storage._steps {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sh_Generated_ShelterQuestStep: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ShelterQuestStep"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "demand"),
    2: .same(proto: "venue"),
    3: .same(proto: "timeWindow"),
    4: .same(proto: "duration"),
  ]

  fileprivate class _StorageClass {
    var _demand: Sh_Generated_ShelterDemand? = nil
    var _venue: Sh_Generated_Venue? = nil
    var _timeWindow: Sh_Generated_TimeWindow? = nil
    var _duration: Int32 = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _demand = source._demand
      _venue = source._venue
      _timeWindow = source._timeWindow
      _duration = source._duration
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._demand)
        case 2: try decoder.decodeSingularMessageField(value: &_storage._venue)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._timeWindow)
        case 4: try decoder.decodeSingularInt32Field(value: &_storage._duration)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._demand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._venue {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _storage._timeWindow {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _storage._duration != 0 {
        try visitor.visitSingularInt32Field(value: _storage._duration, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sh_Generated_ShelterQuestStep, rhs: Sh_Generated_ShelterQuestStep) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._demand != rhs_storage._demand {return false}
        if _storage._venue != rhs_storage._venue {return false}
        if _storage._timeWindow != rhs_storage._timeWindow {return false}
        if _storage._duration != rhs_storage._duration {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sh_Generated_SearchQuestsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SearchQuestsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "params"),
    2: .same(proto: "orderTags"),
  ]

  fileprivate class _StorageClass {
    var _params: Sh_Generated_SearchParams? = nil
    var _orderTags: [String] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _params = source._params
      _orderTags = source._orderTags
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._params)
        case 2: try decoder.decodeRepeatedStringField(value: &_storage._orderTags)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._params {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._orderTags.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._orderTags, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sh_Generated_SearchQuestsRequest, rhs: Sh_Generated_SearchQuestsRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._params != rhs_storage._params {return false}
        if _storage._orderTags != rhs_storage._orderTags {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Sh_Generated_SearchQuestsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SearchQuestsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "quests"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.quests)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.quests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.quests, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Sh_Generated_SearchQuestsResponse, rhs: Sh_Generated_SearchQuestsResponse) -> Bool {
    if lhs.quests != rhs.quests {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
